name: 3-Security-SAST-SCA-SBOM

# This Workflow will submit the application artifact to Veracode for SAST and SCA scan
# It will run manually or automatically after workflow 2-Dockerize-Publish completes.

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2-Dockerize-Publish"]
    types:
      - completed

jobs:
  Security-Scan-SAST-SCA:
    runs-on: ubuntu-latest
    steps:

# Download the most recent build artifact from the 1-Checkout-Build-Artifact worfklow.
      - name: Download Checkout-Build-Artifact Workflow Artifact
        uses: qiwi-forks/action-download-artifact@v2
        with: 
         github_token: ${{secrets.GITHUB_TOKEN}}
         workflow: 1-Checkout-Build-Artifact.yml
         name: verademo_java
        continue-on-error: false

# Listing the folder contents is very handy for troubleshooting      
      - name: List folder contents for visual to confirm artifact file exists
        run: |
         ls -la

# Use the UploadAndScan action to submit the artifact for scanning
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@master
        id: upload_and_scan
        with:
          appname: 'VeraDemo-Java-GitHub'
          createprofile: false
          version: '${{ github.run_id }}'
          criticality: Medium
          filepath: 'verademo.war'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
        continue-on-error: true

# Synch Issues into GitHub Issues.  This will synch the issues from the most recent completed SAST/SCA Policy scan.
# This is fine for most, see more advanced workflow to get more instant feedback if needed.
  Synch-Issues-to-GitHub:
    runs-on: ubuntu-latest
    container: 
      image: veracode/api-signing:latest
    steps:
      - name: Get SAST/SCA/DAST Policy flaws
        run: |
          cd /tmp
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          guid=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?name=VeraDemo-Java-GitHub" | jq -r '._embedded.applications[0].guid') 
          echo GUID: ${guid}
          total_flaws=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True" | jq -r '.page.total_elements')
          echo TOTAL_FLAWS: ${total_flaws}
          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True&size=${total_flaws}" > policy_flaws.json
          
          TOTAL_SCA=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=SCA&severity_gte=4" | jq -r '.page.total_elements')
          echo TOTAL_SCA: ${total_sca}
          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=SCA&severity_gte=4&size=${total_sca}" > sca_issues.json
          
          TOTAL_DAST=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=DAST&violates_policy=True" | jq -r '.page.total_elements')
          echo TOTAL_DAST: ${total_dast}
          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=DAST&violates_policy=True&size=${total_sca}" > dast_flaws.json
     
      - name: Synch SAST flaws to GitHub Issues
        uses: veracode/veracode-flaws-to-issues@v1
        with:
          scan-results-json: '/tmp/policy_flaws.json'
          github-token: ${{ secrets.GH_TOKEN }}     

      - name: Synch DAST vulnerabilities to GitHub Issues  (SCA issue synch in seperate workflow)
        uses: veracode/veracode-flaws-to-issues@v1
        with:
          scan-results-json: '/tmp/dast_flaws.json'
          github-token: ${{ secrets.GH_TOKEN }}    

# Veracode CLI against the container
  Container-Inspection-SBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Veracode Container Scanner
        run: |
          mkdir tmp
          cd tmp
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          ls -la
          ./veracode scan --source /home/runner/work/verademo-java/verademo-java --type directory --format table -o IssuesSource.txt
          ./veracode sbom --source veracodedemolabs/verademo-java-github:latest --type image --format table -o SBOM.txt

# Store security artifacts with build
      - name: Upload security artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SecurityArtifacts
          path: ./tmp/*.txt     

# Running SCA Agent against Repo and Container
  SCA-Agent-Scan-Resuls-Import:
    runs-on: ubuntu-latest
    steps:
    - name: Veracode SCA Dependency Scanning
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      uses: veracode/veracode-sca@v2.0.65
      with:
        github_token: ${{ github.token }}
        update_advisor: true
        create-issues: true
        # A path within the repository where the build definition starts
        path: app
        # Run the SRCCLR with the `--allow-dirty` option
        allow-dirty: true 
    
    - name: SCA Container Scan
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --image veracodedemolabs/verademo-java-github:latest --json=SCA-Container-Results-${{ github.run_id }}.json
      
    - name: Upload artifact with SCA app and container issues for this build
      uses: actions/upload-artifact@v3.1.1
      with:
         name: SCA-Issues-VeraDemoJava-app-container-${{ github.run_id }}
         path: "*.json"
